/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'


export default function Hoofdzaal(props) {
  const { nodes } = useGLTF('./models/hoofdzaal.glb')
  const colorMap = useLoader(TextureLoader, './models/textures/hoofdzaal-baked.jpg')
  colorMap.flipY = false

  return (
    <group {...props} dispose={null}>
      <group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.machineroom.geometry}
        material={nodes.machineroom.material}
        position={[-0.005, 0.584, -1.317]}
        rotation={[0, -1.568, 0]}>
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={ 0 } />
        <Html
          position={ [0.1,1.5,0.25]}
          distanceFactor={6}
          occlude>
           <p className='building-label'>{props.label}</p>
         </Html>
      </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[-0.844, 0, -2.529]}
        >
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={ 0 } />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[-0.844, 0, -2.917]}
        >
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={ 0 } />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube006.geometry}
          material={nodes.Cube006.material}
          position={[-0.895, 0.137, -2.53]}
        >
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={ 0 } />
        </mesh>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube021.geometry}
          material={nodes.Cube021.material}
          position={[-0.896, 0.135, -2.921]}
        >
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={ 0 } />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/hoofdzaal.glb')