/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { SRGBColorSpace } from 'three'

export default function Kunstacademie(props) {
  const { nodes } = useGLTF('/models/kunstacademie-no-materials.glb')
  const colorMap = useLoader(TextureLoader, '/models/textures/kunstacademie-baked.webp')
  colorMap.flipY = false
  colorMap.colorSpace = SRGBColorSpace
  return (
    <group onClick={(e) => {
      e.stopPropagation()
      props.handleClick()
    }} dispose={null}>
      <group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube016.geometry}
        position={[3.105, 0.186, -0.804]}
        rotation={[0, 0.009, -Math.PI]}
        scale={[-0.143, -0.15, -0.241]}
      >
        <Html
          position={ [ -3, 4.5, 0 ]}
          distanceFactor={6}
          occlude>
            <p className='building-label'>kunstacademie</p>
          </Html>
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={props.emissiveIntensity} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube019.geometry}
        position={[2.854, 0.053, -0.637]}
        rotation={[0, 0.009, -Math.PI]}
        scale={[-0.109, -0.062, -0.075]}
      >
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={props.emissiveIntensity} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube024.geometry}
        position={[2.908, 0.044, -0.797]}
        rotation={[0, 0.009, -Math.PI]}
        scale={[-0.055, -0.055, -0.038]}
      >
        <meshStandardMaterial 
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={props.emissiveIntensity} />
      </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kunstacademie-no-materials.glb')