/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF, Html } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { SRGBColorSpace } from 'three'

export default function Mechaniekers(props) {
const { nodes } = useGLTF('/models/mechaniekers-no-materials.glb')
const colorMap = useLoader(TextureLoader, '/models/textures/mechaniekers-baked.webp')
colorMap.flipY = false
colorMap.colorSpace = SRGBColorSpace

  return (
    <group onClick={(e) => {
      e.stopPropagation()
      props.handleClick()
    }} dispose={null}>
      <group
        >
        <mesh
          receiveShadow
          geometry={nodes.mechaniekers.geometry}
        >
          <Html
            
            position={ [-0.85,3.0,0.2]}
            distanceFactor={6}
            occlude>
              <p onClick={(e) => {
              console.log('clicked')
              e.stopPropagation()
              props.handleClick()
            }} className='building-label'>Mechaniekersgebouw</p>
          </Html>
          <meshStandardMaterial 
          roughness={1}
          metalness={0}
          map={colorMap}
          emissive="#BC78FF" 
          emissiveIntensity={props.emissiveIntensity} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/mechaniekers-no-materials.glb')
