/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from "react";
import { useGLTF, Html } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three/src/loaders/TextureLoader";
import { SRGBColorSpace } from "three";

export default function Octagon(props) {
  const { nodes } = useGLTF("models/octagon-no-materials.glb");
  const colorMap = useLoader(
    TextureLoader,
    "models/textures/octagon-baked.webp"
  );
  colorMap.flipY = false;
  colorMap.colorSpace = SRGBColorSpace;
  return (
    <group onClick={(e) => {
      e.stopPropagation()
      props.handleClick()
    }} dispose={null}>
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube018.geometry}
          position={[1.892, 0.036, -0.849]}
          rotation={[0, 0.009, -Math.PI]}
          scale={[-0.109, -0.151, -0.075]}
        >
          <meshStandardMaterial
            map={colorMap}
            emissive="#BC78FF"
            emissiveIntensity={props.emissiveIntensity}
          />
        </mesh>
        <mesh
          geometry={nodes.Circle.geometry}
          position={[1.89, -0.102, -1.122]}
          rotation={[0, -0.375, 0]}
        >
          <Html position={[-0.15, 1.0, 0.15]} distanceFactor={6} occlude>
            <p className="building-label">Octagon</p>
          </Html>
          <meshStandardMaterial
            map={colorMap}
            emissive="#BC78FF"
            emissiveIntensity={props.emissiveIntensity}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("models/octagon-no-materials.glb");
