/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useEffect, useRef } from "react";
import { useGLTF, Html } from "@react-three/drei";
import { useLoader } from "@react-three/fiber";
import { TextureLoader } from "three/src/loaders/TextureLoader";
import { SRGBColorSpace } from "three";

export default function Plong(props) {
  const { nodes } = useGLTF("/models/plong.glb");
  const colorMap = useLoader(
    TextureLoader,
    "/models/textures/plong-baked.webp"
  );
  colorMap.flipY = false;
  colorMap.colorSpace = SRGBColorSpace;

  const label = useRef();

  useEffect(() => {
    props.timeline?.current?.to(
      label.current,
      {
        opacity: 1,
        cursor: "pointer",
        duration: 0.25,
        ease: "power2.out",
      },
      0.25
    );
  }, [label.current]);

  return (
    <group
      onClick={(e) => {
        e.stopPropagation();
        props.handleClick();
      }}
      dispose={null}
    >
      <group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.plong.geometry}
          position={[1.504, 0.12, -0.343]}
          rotation={[0, 0.009, 0]}
        >
          <Html position={[-0.2, 0.6, 0]} distanceFactor={7} occlude>
            <p
              ref={label}
              onClick={(e) => {
                e.stopPropagation();
                props.handleClick();
              }}
              className={`building-label ${props.active ? "building-label--active" : ""}`}
            >
              {props.label}
            </p>
          </Html>
          <meshStandardMaterial
            map={colorMap}
            emissive="#BC78FF"
            emissiveIntensity={props.active ? 3.0 : 0}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/models/plong.glb");
