/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { SRGBColorSpace } from 'three'



export default function MapModel(props) {
  const { nodes} = useGLTF('/models/static-map-bachelors.glb')
  const colorMap = useLoader(TextureLoader, '/models/textures/final-bake.jpg')
  colorMap.flipY = false
  colorMap.colorSpace = SRGBColorSpace
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['building-7-windows'].geometry}
        position={[0.576, 0.423, -0.65]}
        rotation={[0, 0.003, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube013.geometry}
        material={nodes.Cube013.material}
        position={[-0.651, 0.238, 1.084]}
        rotation={[0, 0.009, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle001.geometry}
        material={nodes.Circle001.material}
        position={[-1.093, 2.244, 1.422]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube014.geometry}
        material={nodes.Cube014.material}
        position={[-0.667, 0.133, 1.663]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle002.geometry}
        material={nodes.Circle002.material}
        position={[-1.874, -0.017, 0.935]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={nodes.Cylinder001.material}
        position={[1.481, 0.194, 3.353]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={nodes.Cylinder002.material}
        position={[0.344, 0.307, 3.368]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube008.geometry}
        material={nodes.Cube008.material}
        position={[1.489, 0.33, 1.893]}
        rotation={[0, -1.35, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube015.geometry}
        material={nodes.Cube015.material}
        position={[0.402, 0.088, 1.815]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube017.geometry}
        material={nodes.Cube017.material}
        position={[3.257, 0.14, 0.081]}
        rotation={[0, 0.009, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube026.geometry}
        material={nodes.Cube026.material}
        position={[3.262, 0.08, 0.352]}
        rotation={[0, 0.003, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube027.geometry}
        material={nodes.Cube027.material}
        position={[3.453, 0.068, 0.076]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube028.geometry}
        material={nodes.Cube028.material}
        position={[3.603, 0.123, 0.772]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube029.geometry}
        material={nodes.Cube029.material}
        position={[3.605, 0.033, 1.086]}
        rotation={[0, 0.003, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Plane.geometry}
        material={nodes.Plane.material}
        position={[1.413, 0.021, 0.512]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.middenplein.geometry}
        position={[2.347, 0.023, 0.422]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap} />
      </mesh>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.ground.geometry}
        position={[-0.138, -0.035, -0.012]}
        rotation={[0, -1.568, 0]}
        scale={[5.418, 2.464, 5.418]}
      >
        <meshStandardMaterial 
          map={groundColorMap} />
      </mesh> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube030.geometry}
        position={[0.36, 0.153, -3.614]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube031.geometry}
        position={[0.622, 0.153, -3.609]}
        rotation={[0, -1.568, 0]}   
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube032.geometry}
        position={[1.03, 0.153, -3.607]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube033.geometry}
        position={[0.768, 0.153, -3.611]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube034.geometry}
        position={[1.574, 0.153, -3.624]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube035.geometry}
        position={[1.836, 0.153, -3.62]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube036.geometry}
        position={[0.481, 0.104, -3.756]}
        rotation={[0, 0.003, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube037.geometry}
        position={[0.898, 0.104, -3.757]}
        rotation={[0, 0.003, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube038.geometry}
        position={[1.708, 0.104, -3.759]}
        rotation={[0, 0.003, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube.geometry}
        position={[1.045, 0.164, -0.335]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube022.geometry}
        material={nodes.Cube022.material}
        position={[-1.609, 0.213, -0.511]}
        rotation={[0, 0.015, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Circle003.geometry}
        material={nodes.Circle003.material}
        position={[-1.349, 0.006, -1.692]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}

        position={[0.656, 0.773, -1.939]}
        rotation={[0, 0.009, 0]}
      >
        <meshStandardMaterial 
          map={officeBuildingColorMap}/>
      </mesh> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube020.geometry}
        position={[0.664, 1.662, -1.807]}
        rotation={[0, -1.568, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('/models/static-map-bachelors.glb')
