/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three/src/loaders/TextureLoader'
import { SRGBColorSpace } from 'three'
export default function OfficeBuilding(props) {
  const { nodes } = useGLTF('models/office-building.glb')
  const colorMap = useLoader(TextureLoader, 'models/textures/office-building-baked.jpg')
  colorMap.flipY = false
  colorMap.colorSpace = SRGBColorSpace
  
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cube001.geometry}
        material={nodes.Cube001.material}
        position={[0.656, 0.773, -1.939]}
        rotation={[0, 0.009, 0]}
      >
        <meshStandardMaterial 
          map={colorMap}/>
      </mesh>
    </group>
  )
}

useGLTF.preload('models/office-building.glb')