/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React from 'react'
import { Clone, useGLTF } from '@react-three/drei'

export default function Trees(props) {
const tree = useGLTF('/models/compressed_tree.glb')
  return (
       <>
         <Clone object={ tree.scene } position-x= {-1.5} position-z= {-0.55} />
         <Clone object={ tree.scene } position-x= {0}/>
         <Clone object={ tree.scene } position-x= {-0.05}  position-z= {0.12}/>
      </>
  )
}

useGLTF.preload('/models/compressed_tree.glb')